### ISSUE TITLE
Contact and publications appear in two TOCs

### ISSUE THREAD

**Issue by niksirbi** [brainglobe/website#26]
The "Contact" and "Publications" pages appear in two TOCs: in "About" and in "Resources".

I don't know if this was intentional, but it causes some weird behaviour on the navigation sidebar.
For example, if one is on "About" and clicks on "Contact" on the sidebar, the sidebar TOC changes to that of "Resources", etc.

I'd suggest keeping these two pages only in about.

**Comment by adamltyson** [comment]
It was intentional, I didn't realise it had side-effects. Fixed in https://github.com/brainglobe/website/pull/27
